### ISSUE TITLE
Reading RAW RFID File error when emulating RAW RFID

### ISSUE THREAD

**Issue by alexdotpink** [DarkFlippers/unleashed-firmware#444] opened 2023-04-28 13:06 UTC
### Describe the bug.

When I try to emulate a RAW RFID file, I get the following error: `Reading RAW RFID File error`.
I'm using `unlshd-046`.

### Reproduction

1. Switch on
2. Go to 125kHz RFID
3. Go to Extra Actions
4. Select Read RAW RFID data
5. Scan your RFID tag
6. Go back and select Emulate RAW RFID Data
7. Try emulating your RFID tag

**Comment by xMasterX** [comment] 2023-05-22 01:06
Can't replicate, send your raw files

**Comment by Leptopt1los** [comment] 2024-01-06 17:33
We are closing the issue because you did not provide files for testing. if the problem is reproduced on the latest firmware version - reopen this issue

**Closed as completed by Leptopt1los** 2024-01-06 17:33 UTC
Labels: bug, question
