### ISSUE TITLE
NFC reader not using MF keys from user dict

### ISSUE THREAD

**Issue by iter8tor** [DarkFlippers/unleashed-firmware#396] opened 2023-03-24 08:26 UTC
### Describe the bug.

I'm using several MF 1k cards at the moment and saved all the access keys into the user dict file.
On the latest release, the NFC reader app only "finds" 18/32 sector keys for these cards. This doesn't happen on other firmwares.

### Reproduction

1. Switch on, open NFC app, then Read card
2. The app tries to read the sectors using the keys from the user dict
3. The app fails to unlock all the sectors, as it cannot read all the keys.

**Comment by Chemicalius** [comment] 2023-03-24 10:07
It might be the same issue as here: https://github.com/flipperdevices/flipperzero-firmware/issues/2413

**Comment by iter8tor** [comment] 2023-03-24 13:54
> It might be the same issue as here: [flipperdevices/flipperzero-firmware#2413](https://github.com/flipperdevices/flipperzero-firmware/issues/2413)

I tried emulating the card with a PM3 and the issue is still present.
Haven't tried the official firmware, but I just switched to Xtreme and the issue is gone.

**Comment by xMasterX** [comment] 2023-03-24 16:45
Issue can't be reproduced, my user dict are working file, latest 038 release
Have fun with other firmware, this totally unrelated to this issue
If you can reproduce it every time - format your microsd, and try with OFW
If issue is present - then we can talk, 
As for now its just sounds like you trying to advertise xtreme fw by creating issue with non existing bug
Since you are using empty account
"Opened this issue (their first ever)"

**Comment by iter8tor** [comment] 2023-03-24 16:54
So, new users shouldn't have any issues, right?
TBH I liked unleashed better than other firmwares, but not being able to read my cards is a dealbreaker for me.
Anyway, good luck with your development.

**Comment by xMasterX** [comment] 2023-03-24 16:56
We will try to reproduce it in all possible ways, for now this sounds like exactly as i said in previous message, non existing bug

**Comment by xMasterX** [comment] 2023-03-24 17:26
<img width="782" alt="Screenshot 2023-03-24 at 20 24 11" src="https://user-images.githubusercontent.com/10697207/227597168-d27157ff-0281-4e2b-a4c0-443217b9af39.png">


Now I see why this works for you in the xtreme, their latest release was released BEFORE nfc changes

So, now i see a reason why this can happen

**Comment by xMasterX** [comment] 2023-03-24 17:27
Their release was done before this commit

https://github.com/DarkFlippers/unleashed-firmware/commit/e90042368f941f2c167563444fdb5cf22a5da9ad

**Comment by iter8tor** [comment] 2023-03-24 17:43
Well, I'm glad you sorted this out.
Can't wait for 039.

**Comment by xMasterX** [comment] 2023-03-24 17:45
When i fix that ill post an update here, sorry for misunderstanding at first, since it was not easy to replicate with all my test cards, i made a new one and found that it can auth only 1 sector from user dict then if next sector had different custom keys it will auth and skip it for some strange reason

**Comment by iter8tor** [comment] 2023-03-24 17:52
> When i fix that ill post an update here, sorry for misunderstanding at first, since it was not easy to replicate with all my test cards, i made a new one and found that it can auth only 1 sector from user dict then if next sector had different custom keys it will auth and skip it for some strange reason

It is indeed a strange behavior. It auths 2 keys, then tries more sectors, then seem to find a third key, then soon the number drops to 1. After it gets to sector 2, doesn't try any new keys, as the number of "found" keys is always 2.

**Comment by xMasterX** [comment] 2023-03-25 04:25
Should be fixed in latest dev build

please install using this link and verify

[Dev build 435e](https://lab.flipper.net/?url=https://unleashedflip.com/fw_extra_apps/flipper-z-f7-update-435e.tgz&channel=dev-cfw&version=435e)

**Closed as completed by xMasterX** 2023-03-25 04:25 UTC
Labels: bug

**Comment by FoxLy1312** [comment] 2023-03-25 04:29
Its not that hard to brew it yourself, its kind of fun :3
Am 24. März 2023, 18:43 +0100 schrieb iter8tor ***@***.***>:
