### ISSUE TITLE
Adding bad USB over bluetooth functionality

### ISSUE THREAD

**Issue by MichaelK-F** [DarkFlippers/unleashed-firmware#439] opened 2023-04-24 09:59 UTC
### Description of the feature you're suggesting.

In the Xtreme firmware, in the config menu for bad USB (renamed to bad KB), there is the option to use bluetooth instead of USB. See [https://github.com/ClaraCrazy/Flipper-Xtreme#bad-keyboard](https://github.com/ClaraCrazy/Flipper-Xtreme#bad-keyboard)
It would be extremely useful to have this added to the unleashed firmware. 

This would be extending on the functionality of the already existing bad USB application on the unleashed firmware.

**Comment by ClaraCrazy** [comment] 2023-04-24 10:09
:zzz:

**Comment by xMasterX** [comment] 2023-04-25 00:26
Duplicate of #350 #346 and other similar requests, #346 is open one, im closing this, continue your discussion in #346

**Closed as completed by xMasterX** 2023-04-25 00:26 UTC
Labels: feature request
