### ISSUE TITLE
BLE Spam doesn't work partially.

### ISSUE THREAD

**Issue by AztecCodes** [DarkFlippers/unleashed-firmware#764] opened 2024-06-14 09:02 UTC
---

**Comment by xMasterX** [comment] 2024-06-14 09:40
Hello, what do you mean "doesn't work" ?
If you are not aware, latest ios and android versions now includes fix for this
This is not a BUG

**Closed as completed by xMasterX** 2024-06-14 09:40 UTC
Labels: bug

**Comment by AztecCodes** [comment] 2024-06-14 11:25
@xMasterX Sorry for asking this here, however is there any place where I can ask something about the Discord Server? I can't find any other possibility to contact someone who is in charge.

**Comment by xMasterX** [comment] 2024-06-14 11:26
> @xMasterX Sorry for asking this here, however is there any place where I can ask something about the Discord Server? I can't find any other possibility to contact someone who is in charge.

What do you mean? You have been banned in our discord and can't join?

**Comment by AztecCodes** [comment] 2024-06-14 11:33
@xMasterX I am not sure. I can't see the Discord Server anymore in my list and the invitation doesn't work anymore. So I guess that I got banned.

**Comment by xMasterX** [comment] 2024-06-14 11:34
> @xMasterX I am not sure. I can't see the Discord Server anymore in my list and the invitation doesn't work anymore. So I guess that I got banned.

Share your discord username

**Comment by AztecCodes** [comment] 2024-06-14 11:35
@xMasterX azteccodes

**Comment by xMasterX** [comment] 2024-06-14 11:39
> @xMasterX azteccodes

you was banned for shit posting (spamming) in general channel

I'll give you 2nd chance, read server rules again after joining and follow them

Next time ban will be permanent

**Comment by AztecCodes** [comment] 2024-06-14 11:40
@xMasterX Thank you very much. This is very kind.
