### ISSUE TITLE
Bravia TV's no longer compatible in IR universal remote

### ISSUE THREAD

**Issue by fOmey** [DarkFlippers/unleashed-firmware#207] opened 2022-12-15 06:13 UTC
### Describe the bug.

Since the infared assets update (commit: 6f9f0dbe6ee236378dcb7bd302e2f63ed33905fb) Sony Bravia TV's no longer appear to be supported in the universal remote.

I've tested with power toggle, mute & volume controls.

### Reproduction

1. Open IR universal remote.
2. Point flipper at Sony Bravia TV.
3. Toggle a button.

**Comment by GideonWolfe** [comment] 2022-12-19 02:01
I've also been noticing the Universal Remote working less after switching to Unleashed.  Others have [noticed the same](https://www.reddit.com/r/flipperzero/comments/zohsfn/universal_remote_not_effective/)

**Comment by UberGuidoZ** [comment] 2022-12-19 22:17
Interesting. Likely because something was changed in the way things were handled by Official. And since Unleashed is built off the dev base, something may need to be adjusted.

@fOmey Do you have a capture of the actual remote for comparison? I want to make sure the codes are still in the Universal file. For example, here's the POWER on a Sony Bravia XBR TV:
```
Filetype: IR signals file
Version: 1
# 
name: Power
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 15 00 00 00
```
It does exist in the tv.ir Universal file, but I have confirmed it's not working on the POWER. Speaking to Amec0e now about it so we can figure out where things stopped working. Thank you.

**Comment by fOmey** [comment] 2022-12-27 08:42
> Interesting. Likely because something was changed in the way things were handled by Official. And since Unleashed is built off the dev base, something may need to be adjusted.
> 
> @fOmey Do you have a capture of the actual remote for comparison? I want to make sure the codes are still in the Universal file. For example, here's the POWER on a Sony Bravia XBR TV:
> 
> ```
> Filetype: IR signals file
> Version: 1
> # 
> name: Power
> type: parsed
> protocol: SIRC
> address: 01 00 00 00
> command: 15 00 00 00
> ```
> 
> It does exist in the tv.ir Universal file, but I have confirmed it's not working on the POWER. Speaking to Amec0e now about it so we can figure out where things stopped working. Thank you.

@UberGuidoZ Sorry about the delayed response, this is a dump of my remote:

```
Filetype: IR signals file
Version: 1
# 
name: Pwr
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 15 00 00 00
# 
name: VolUp
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 12 00 00 00
# 
name: VolDown
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 13 00 00 00
# 
name: ChUp
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 10 00 00 00
# 
name: ChDown
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 11 00 00 00
# 
name: Mute
type: parsed
protocol: SIRC
address: 01 00 00 00
command: 14 00 00 00

```

**Comment by bunk3r** [comment] 2022-12-30 17:49
Don't know why, but on dev-215 the Universal Remote standby command works again on my Bravia, but not the others (vol, mute, etc..)

**Comment by xMasterX** [comment] 2022-12-30 22:38
> Don't know why, but on dev-215 the Universal Remote standby command works again on my Bravia, but not the others (vol, mute, etc..)

We fixed power button by adding raw recording of it, but other buttons for sony, using SIRC protocol doesn’t work unless they captured in RAW

**Comment by ToXiCRaTt** [comment] 2023-01-07 08:57
Same here no response with universal remote.

**Comment by UberGuidoZ** [comment] 2023-01-07 18:31
> Same here no response with universal remote.

For what model TV? We’ve tested on a handful that we’re not working before, but thanks to xMasterX idea, SIRC is now working. (Was an issue introduced from Official.)

**Comment by xMasterX** [comment] 2023-01-19 18:30
Fixed in latest release

**Closed as completed by xMasterX** 2023-01-19 18:30 UTC
Labels: bug
