### ISSUE TITLE
Is the firmware dead

### ISSUE THREAD

**Issue by clover-repos** [DarkFlippers/unleashed-firmware#650] opened 2023-11-11 21:35 UTC
### Describe the bug.

Is the firmware dead?

### Reproduction

no updates for a month last file update was three weeks ago so whats the deal?

**Comment by xMasterX** [comment] 2023-11-12 09:08
Yes

**Comment by xMasterX** [comment] 2023-11-12 09:12
If I can't have any breaks due to my health problems, you can say anything, dead, abandoned, and other things
If you haven't seen my post in discord and telegram ill say again here, most of the work is already done locally, i'm not publishing it on github yet

**Comment by assasinfil** [comment] 2023-11-21 19:59
Is the issue dead?)

**Comment by xMasterX** [comment] 2023-11-21 21:16
> Is the issue dead?)

dev branch looks alive, but `release` branch is dead :(((
still actual issue then

**Comment by mgrybyk** [comment] 2023-11-22 15:23
Do you think it still makes sense to release even though the NFC seems to be badly broken in the upstream?

I mean they did really great job but it requires some time to deal with multiple regressions.
I also believe it's a lot of work to sync with upstream easily taking into account there were more than 500 files changed.

**Comment by xMasterX** [comment] 2023-11-26 23:47
> Do you think it still makes sense to release even though the NFC seems to be badly broken in the upstream?
> 
> I mean they did really great job but it requires some time to deal with multiple regressions. I also believe it's a lot of work to sync with upstream easily taking into account there were more than 500 files changed.

Release won't be done while there are issues with new stack
But merge was already done in `dev` branch, and some work with plugin fixes too, in apps repo
Couple problems are still in place, when we finish with them, only then it will be possible to make the release

**Comment by mgrybyk** [comment] 2023-11-27 09:27
@xMasterX thanks a lot for your hard work! 👍

**Comment by stremovskyy** [comment] 2023-11-28 16:43
> @xMasterX thanks a lot for your hard work! 👍

+1

**Comment by GloryToGlorzo69** [comment] 2023-12-08 08:48
Take a look into the Discord
[https://lab.flipper.net/?url=https://unleashedflip.com/fw_extra_apps/flipper-z-f7-update-874e.tgz&channel=dev-cfw&version=874e](https://lab.flipper.net/?url=https://unleashedflip.com/fw_extra_apps/flipper-z-f7-update-874e.tgz&channel=dev-cfw&version=874e) is the newest unleashed-version

**Comment by xarinatan** [comment] 2023-12-10 00:44
I'm glad to hear there's still work done on the firmware, I didn't realize there was such a huge overhaul underway on the NFC parts- Good luck on the journey! I also became a Patreon subscriber since I've been putting off on doing that for too long, hope it helps a little.

Thanks to all involved for building this, it's sincerely a great part of the Flipper Zero ecosystem that I wouldn't want to see it do without.

**Comment by xMasterX** [comment] 2023-12-17 04:55
Looks like release came out recently - https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-066
Issue seems to be not actual, time to close it now

**Closed as completed by xMasterX** 2023-12-17 04:55 UTC
Labels: bug
